version: "3.7"
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgressql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mypostgre
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=apass
